/**
 * QR Studio Style Presets
 * Curated presets for instant professional looks
 */

export const QR_PRESETS = [
  {
    id: 'phongdang-brand',
    name: 'PhongDang Blue',
    dotsType: 'extra-rounded',
    dotsColorType: 'gradient-linear',
    dotsColor1: '#38bdf8',
    dotsColor2: '#6366f1',
    dotsGradientAngle: 135,
    cornersSquareType: 'extra-rounded',
    cornersSquareColor: '#6366f1',
    cornersDotType: 'dot',
    cornersDotColor: '#38bdf8',
    bgColor: '#ffffff',
    bgTransparent: false,
    frameStyle: 'bottom-badge',
    frameText: 'QUÉT MÃ TRUY CẬP',
    frameColor: '#6366f1',
    frameTextColor: '#ffffff'
  },
  {
    id: 'cyber-neon',
    name: 'Cyber Neon',
    dotsType: 'dots',
    dotsColorType: 'gradient-linear',
    dotsColor1: '#06b6d4',
    dotsColor2: '#a855f7',
    dotsGradientAngle: 45,
    cornersSquareType: 'dot',
    cornersSquareColor: '#06b6d4',
    cornersDotType: 'dot',
    cornersDotColor: '#a855f7',
    bgColor: '#090d16',
    bgTransparent: false,
    frameStyle: 'scan-me',
    frameText: 'SCAN ME',
    frameColor: '#06b6d4',
    frameTextColor: '#090d16'
  },
  {
    id: 'minimal-mono',
    name: 'Minimal Mono',
    dotsType: 'rounded',
    dotsColorType: 'single',
    dotsColor1: '#090d16',
    dotsColor2: '#090d16',
    cornersSquareType: 'rounded',
    cornersSquareColor: '#090d16',
    cornersDotType: 'square',
    cornersDotColor: '#090d16',
    bgColor: '#ffffff',
    bgTransparent: false,
    frameStyle: 'none',
    frameText: '',
    frameColor: '#090d16',
    frameTextColor: '#ffffff'
  },
  {
    id: 'emerald-luxury',
    name: 'Emerald Tech',
    dotsType: 'classy-rounded',
    dotsColorType: 'gradient-linear',
    dotsColor1: '#10b981',
    dotsColor2: '#047857',
    dotsGradientAngle: 135,
    cornersSquareType: 'extra-rounded',
    cornersSquareColor: '#047857',
    cornersDotType: 'dot',
    cornersDotColor: '#10b981',
    bgColor: '#ffffff',
    bgTransparent: false,
    frameStyle: 'top-banner',
    frameText: 'KẾT NỐI NHANH',
    frameColor: '#10b981',
    frameTextColor: '#ffffff'
  },
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    dotsType: 'dots',
    dotsColorType: 'gradient-linear',
    dotsColor1: '#f43f5e',
    dotsColor2: '#f59e0b',
    dotsGradientAngle: 90,
    cornersSquareType: 'extra-rounded',
    cornersSquareColor: '#f43f5e',
    cornersDotType: 'dot',
    cornersDotColor: '#f59e0b',
    bgColor: '#ffffff',
    bgTransparent: false,
    frameStyle: 'bottom-badge',
    frameText: 'QUÉT NGAY',
    frameColor: '#f43f5e',
    frameTextColor: '#ffffff'
  },
  {
    id: 'vietqr-napas',
    name: 'VietQR Napas',
    dotsType: 'square',
    dotsColorType: 'single',
    dotsColor1: '#005baa',
    dotsColor2: '#005baa',
    cornersSquareType: 'square',
    cornersSquareColor: '#e01e2b',
    cornersDotType: 'square',
    cornersDotColor: '#005baa',
    bgColor: '#ffffff',
    bgTransparent: false,
    frameStyle: 'bottom-badge',
    frameText: 'THANH TOÁN VIETQR',
    frameColor: '#005baa',
    frameTextColor: '#ffffff'
  },
  {
    id: 'coffee-mocha',
    name: 'Coffee Mocha',
    dotsType: 'rounded',
    dotsColorType: 'gradient-linear',
    dotsColor1: '#854d0e',
    dotsColor2: '#451a03',
    dotsGradientAngle: 135,
    cornersSquareType: 'rounded',
    cornersSquareColor: '#451a03',
    cornersDotType: 'dot',
    cornersDotColor: '#854d0e',
    bgColor: '#fefce8',
    bgTransparent: false,
    frameStyle: 'scan-me',
    frameText: 'MENU / ORDER',
    frameColor: '#854d0e',
    frameTextColor: '#ffffff'
  },
  {
    id: 'glass-transparent',
    name: 'Transparent Pure',
    dotsType: 'classy',
    dotsColorType: 'single',
    dotsColor1: '#ffffff',
    dotsColor2: '#ffffff',
    cornersSquareType: 'extra-rounded',
    cornersSquareColor: '#ffffff',
    cornersDotType: 'dot',
    cornersDotColor: '#ffffff',
    bgColor: 'transparent',
    bgTransparent: true,
    frameStyle: 'none',
    frameText: '',
    frameColor: '#ffffff',
    frameTextColor: '#090d16'
  }
];
